# Generated by Django 4.2.1 on 2023-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
