# Generated by Django 4.2.1 on 2023-06-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
