# Generated by Django 4.2.1 on 2023-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
