# Generated by Django 4.2.1 on 2023-07-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_train_date_train_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('berth', models.CharField(max_length=20)),
                ('acCategory', models.CharField(max_length=50)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.train')),
            ],
        ),
    ]
